package docs

// @title           TopDoctors API
// @version         1.0
// @description     API for managing patient diagnoses
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8080
// @BasePath  /v1

// @securityDefinitions.apikey Bearer
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token.

// This is a placeholder function to hold the Swagger annotations.
// The actual Swagger docs will be generated by swag init.
func SwaggerInfo_swagger() {}
